@MultiAuthentication_HostAddress = http://localhost:5115

GET {{MultiAuthentication_HostAddress}}/authenticationsamples/
Accept: application/json

###

GET {{MultiAuthentication_HostAddress}}/authenticationsamples/
Accept: application/json,
X-API-KEY: "11111111111111111111111111111111"

###

GET {{MultiAuthentication_HostAddress}}/authenticationsamples/
Accept: application/json,
Authorization: Bearer 1d93f661c4b241e39f0b0e8fb177ffae

###
