@MultiAuthentication_HostAddress = http://localhost:5115

GET {{MultiAuthentication_HostAddress}}/authentication/single-scheme
Accept: application/json,
X-ORGANIZATION-ID: "1d93f661c4b241e39f0b0e8fb177ffae"

###

GET {{MultiAuthentication_HostAddress}}/authentication/multi-authentication-scheme
Accept: application/json

###

GET {{MultiAuthentication_HostAddress}}/authentication/multi-authentication-scheme
Accept: application/json,
X-API-KEY: "11111111111111111111111111111111"

###

GET {{MultiAuthentication_HostAddress}}/authentication/multi-authentication-scheme
Accept: application/json,
Authorization: Bearer 1d93f661c4b241e39f0b0e8fb177ffae

###


GET {{MultiAuthentication_HostAddress}}/authentication/policy-with-multi-scheme
Accept: application/json,
Authorization: Bearer 1d93f661c4b241e39f0b0e8fb177ffae

###

